name: twitchat-ds
channels:
  - pytorch
  - conda-forge
dependencies:
  - python==3.9
  - pip==21.2.4
  - hdbscan
  - umap-learn
  - sentence-transformers==2.1.0
  - tokenizers==0.10.3
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pip:
    - -r requirements/dev.txt
    - -e .
