name: Testing

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - python-version: 3.6
          #   tox-env: 'py36'
          # - python-version: 3.7
          #   tox-env: 'py37, docs, flake8'
          - python-version: 3.8
            tox-env: 'py38, docs, flake8'

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run Tox with envs ${{ matrix.tox-env }}
        env:
          TOXENV: ${{ matrix.tox-env }}
        run: tox
